<?php

/**
 * @file Commerce Invoice Receipt - Installation file.
 */
 
/**
 * Implements hook_install().
 */
function commerce_invoice_receipt_install() {
  $config = 'system.mail';
  $config->set('commerce_invoice_receipt', 'InvoiceMailSystem');
  $config->save();
}

/**
 * Implements hook_uninstall().
 */
function commerce_invoice_receipt_uninstall() {
  config_clear('system.mail', 'commerce_invoice_receipt');
}
